spring.application.name=workpilot-backend
# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/workpilot
spring.datasource.username=postgres
spring.datasource.password=Becommited@123

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# SQL Logs
spring.jpa.show-sql=true

# Disable Open Session In View
spring.jpa.open-in-view=false

# Hibernate SQL Formatting
spring.jpa.properties.hibernate.format_sql=true

# JWT Access Token
jwt.access.secret=8b4f9d2c6a1e7f3b9c5d8e2f4a6b1c9d8e3f7a2b5c6d9e1f
jwt.access.expiration=900000

# JWT Refresh Token
jwt.refresh.secret=4c7e2a9d8f1b6c3e5a7d9f2b8c4e1a6d7f3b5c9e2a8d6f1b
jwt.refresh.expiration=2592000000