spring.application.name=workpilot-backend
# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/workpilot
spring.datasource.username=postgres
spring.datasource.password=Becommited@123

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# SQL Logs
spring.jpa.show-sql=true

# Disable Open Session In View
spring.jpa.open-in-view=false

# Hibernate SQL Formatting
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=8b4f9d2c6a1e7f3b9c5d8e2f4a6b1c9d8e3f7a2b5c6d9e1f
jwt.expiration=86400000