spring.application.name=workpilot-backend
# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/workpilot
spring.datasource.username=postgres
spring.datasource.password=Becommited@123

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# SQL Logs
spring.jpa.show-sql=true

# Disable Open Session In View
spring.jpa.open-in-view=false

# Hibernate SQL Formatting
spring.jpa.properties.hibernate.format_sql=true